method: grid
metric:
  name: training/episode_return
  goal: maximize
parameters:
  env_id:
    value: "CustomHopper-source-v0"

  n_episodes:
    value: 100000


  actor_critic:
    values: [true]

  baseline:
    values: [20.0]

  device:
    value: "cuda"

  seed:
    values: [42]
