buffer_size: 300          # Buffer size
warmup_episodes: 750      # Episodes before adv_beta starts
limit_percentage: 0.3     # Mass randomization range: +/- 30% 
mix_ratio: 0.5            # Mix ratio
tau: 0.1                  # Soft update 
max_alpha_beta: 80.0      # Upper bound on alphas and betas
failure_percentile: 20    # Threshold of rewards under which are considered failures
fit_interval: 30          # Episodes between each beta distribution update
