method: grid
metric:
  name: rollout/ep_rew_mean
  goal: maximize
parameters:
  env_id:
    value: "CustomHopper-source-v0"
  policy:
    value: "MlpPolicy"
  seed:
    values: [42,43,44]
  dr_method:
    values: ["none", "udr", "adv_beta"]

  # Training parameters
  total_timesteps:
    value: 1000000
  learning_starts:
    value: 10000
  train_freq:
    value: 1
  gradient_steps:
    value: 1
  batch_size:
    value: 256
  device:
    value: "auto"

  # Replay buffer
  buffer_size:
    value: 1000000

  # Policy network architecture
  policy_pi_layer1:
    value: 256
  policy_pi_layer2:
    value: 256
  policy_qf_layer1:
    value: 256
  policy_qf_layer2:
    value: 256
  policy_activation_fn:
    value: "ReLU"

  # Hyperparameters
  gamma:
    value: 0.99
  tau:
    value: 0.005
  target_update_interval:
    value: 1
  ent_coef:
    value: "auto"
  target_entropy:
    value: "auto"

  # Verbose
  verbose:
    value: 1